# docker run -d --rm --name playmongo -p 27018:27017 -v mongodbdata:/data/db mongo

version: "3.8"

services:
  mongo:
    image: mongo
    container_name: playmongo
    ports:
      - 27018:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
